#!/bin/bash
# a batch job submission code for recon-all in ALCF-Theta
# usage: recon_1.#!/bin/sh
#
#!/bin/bash

hr=24

list=$1 #e.g., list_file_t1w.txt
N=`wc ${1} | awk '{print $1}'`
threads=64
#threadsX2=$((${threads}*2))

nki=/lus/theta-fs0/projects/AD_Brain_Imaging/anal/NKI/data

CMD_batch=/lus/theta-fs0/projects/AD_Brain_Imaging/anal/NKI/embarc/job/cmd1.batch.recon.${list}
rm -rf $CMD_batch

#######################################################################################################
cat<<EOC >$CMD_batch
#!/bin/bash
#COBALT -t 00:30:00
#COBALT -n $N
#COBALT --attrs mcdram=cache:numa=quad:ssds=required:ssd_size=10
#COBALT -A AD_Brain_Imaging
#COBALT -M jiook.cha@nyspi.columbia.edu
#COBALT ATP_ENABLED=1
echo start............................................


EOC

#######################################################################################################

i=1
for s in `cat /lus/theta-fs0/projects/AD_Brain_Imaging/anal/NKI/embarc/\$list`

do
  #s=`echo $SUBJECT | egrep -o '[0-9]{8}'`
  CMD=/lus/theta-fs0/projects/AD_Brain_Imaging/anal/NKI/embarc/job/cmd1.recon.t${threads}.${s}
  rm -rf $CMD

  LOG=/lus/theta-fs0/projects/AD_Brain_Imaging/anal/NKI/embarc/job/log.cmd1.recon.t${threads}.${s}
  rm -rf $LOG

  subject=`echo $s | cut -d "_" -f1`
  sess=`echo $s | cut -d "_" -f2`
  T1=/lus/theta-fs0/projects/AD_Brain_Imaging/anal/NKI/data/$subject/$sess/anat/${s}.nii.gz

cat<<EOA >$CMD
#!/bin/bash
source ~/.bashrc
FREESURFER_HOME=/lus/theta-fs0/projects/AD_Brain_Imaging/app/freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.sh
SUBJECTS_DIR=/local/scratch/
ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=$threads

################################################################################
# Executes command with a timeout
# Params:
#   $1 timeout in seconds
#   $2 command
# Returns 1 if timed out 0 otherwise
######################## THIS DID NOT WORK #######################
#timeout() {

#    time=\$1

    # start the command in a subshell to avoid problem with pipes
    # (spawn accepts one command)
#    command="/bin/sh -c \"\$2\""

#    expect -c "set echo \"-noecho\"; set timeout $time; spawn -noecho $command; expect timeout { exit 1 } eof { exit 0 }"

#    if [ \$? = 1 ] ; then
#        echo "Timeout after \${time} seconds"
#    fi

#}
################################################################################
#command & pid=\$! ; sleep 5 && kill $pid
recon-all -all -hippocampal-subfields-T1 -s ${subject}_${sess} -i ${T1} -parallel -openmp ${threads} & pid=\$!

#sleep $((${hr}*3600-600)) && kill \$pid
sleep 60 && kill \$pid

echo "now fetching the recon-all files to SCRATCH space"
source=/local/scratch/${subject}_${sess}
target=/lus/theta-fs0/projects/AD_Brain_Imaging/anal/NKI/fs
cp -rvf \${source} \${target}

EOA

  ################################################## END OF CMD##########################################################
  chmod +x $CMD

  echo "aprun -n 1 -N 1 -d ${threads} -j $((${threads}/64)) -cc depth -e OMP_NUM_THREADS=$threads $CMD > $LOG 2>&1 &">>$CMD_batch

  echo "sleep 0.1">>$CMD_batch
  i=$(($i+1))
  echo $i
  #echo "execute $CMD_sub"

done

echo "wait" >> $CMD_batch
### batch submission

echo $CMD_batch
chmod +x $CMD_batch
echo qsub $CMD_batch
